service: crud-server

package:
  patterns:
    - ./**/*.py
  exclude:
    - node_modules/**
    - venv/**
    - __pycache__/**

provider:
  name: aws
  region: eu-north-1
  versionFunctions: false
  timeout: 30
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'secretsmanager:GetSecretValue'
          Resource:
            - '*'

functions:
  health:
    runtime: python3.8
    handler: src/health_check/handler.main
    layers:
      - arn:aws:lambda:eu-north-1:600377480982:layer:sqlalchemy:7
    events:
      - httpApi:
          cors: true
          method: GET
          path: /hello
    environment:
      STAGE: ${sls:stage}
  create:
    runtime: python3.8
    handler: src/user/create/handler.main
    layers:
      - arn:aws:lambda:eu-north-1:600377480982:layer:sqlalchemy:7
    events:
      - httpApi:
          cors: true
          method: POST
          path: /create_user
    environment:
      STAGE: ${sls:stage}
  read:
    runtime: python3.8
    handler: src/user/read/handler.main
    layers:
      - arn:aws:lambda:eu-north-1:600377480982:layer:sqlalchemy:7
    events:
      - httpApi:
          cors: true
          method: GET
          path: /get_users
    environment:
      STAGE: ${sls:stage}
  update:
    runtime: python3.8
    handler: src/user/update/handler.main
    layers:
      - arn:aws:lambda:eu-north-1:600377480982:layer:sqlalchemy:7
    events:
      - httpApi:
          cors: true
          method: PATCH
          path: /update_user/{id}
    environment:
      STAGE: ${sls:stage}
  delete:
    runtime: python3.8
    handler: src/user/delete/handler.main
    layers:
      - arn:aws:lambda:eu-north-1:600377480982:layer:sqlalchemy:7
    events:
      - httpApi:
          cors: true
          method: DELETE
          path: /delete_user/{id}
    environment:
      STAGE: ${sls:stage}
