"""create_users_table

Revision ID: f7c7c1e4b8fd
Revises: 
Create Date: 2023-12-12 17:25:27.803181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7c7c1e4b8fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('mob_number', sa.String(), nullable=True),
    sa.Column('pan_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'pan_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
